export const SERVICE_LIST_PENDING = "SERVICE_LIST_PENDING";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_ERROR = "SERVICE_LIST_ERROR";
export const PROVIDER_LIST_PENDING = "PROVIDER_LIST_PENDING";
export const PROVIDER_LIST_SUCCESS = "PROVIDER_LIST_SUCCESS";
export const PROVIDER_LIST_ERROR = "PROVIDER_LIST_ERROR";
export const SELECTED_SERVICE_SUCCESS = "SELECTED_SERVICE_SUCCESS";
export const SELECTED_SERVICE_PENDING = "SELECTED_SERVICE_PENDING";
export const SELECTED_SERVICE_ERROR = "SELECTED_SERVICE_ERROR";

